### ISSUE TITLE
Inhance import system and folder structure 

### ISSUE THREAD

**Issue by YousefAldabbas** [igorbenav/FastAPI-boilerplate#41]
**Inhance Import** 
condensing import statements for brevity:
`from app.core import async_get_db, TokenData, is_rate_limited, logging`
This makes imports more concise and groups related items together

**folder structure** 
Moving schemas inside the version folder could enhance the overall project organization. It might make the versioning more intuitive.
I believe middlewares should be in separate folder thats tell what it contain not like cache middleware its inside app/core/cache.py 
Also exceptions file should be folder for each "source of error" not sure about the right word for it but for other services/third parties should be in service.py file (as example) inside exceptions folder users as well UserNotFound  as example

**logging System** 
logger configrations are on a file but logger object is being declared on each folder you are using it in 
this code from rate_limit.py file 
```
from app.core.logger import logging
from app.schemas.rate_limit import sanitize_path

logger = logging.getLogger(__name__)

pool: ConnectionPool | None = None
client: Redis | None = None

logger = logging.getLogger(__name__) # its being declared twice
```
my suggestion will make it easier u will be only need to import the logger (object) 
`from  app.core import ( logger, ...)`

* This is my first time opening a github issue
* sorry for my bad english

**Comment by igorbenav** [comment]
Hey, Yousef, thanks for the issue🎉! Could you please open a sepparate issue for each of the suggestions? It's best for organizing thoughts and keeping the conversation compartmentalized.

**Comment by YousefAldabbas** [comment]
i will close this issue since i opened anothers
