### ISSUE TITLE
Disable automatic table creation

### ISSUE THREAD

**Issue by ahonnecke** [igorbenav/FastAPI-boilerplate#84]
I'm running this inside of docker-compose, and I want more control over the migrations.  It seems to re-create the "initial" tables (user, tier, post) every time I perform `docker-compose up`.

I don't want it to do that, I want to be able to run alembic (from inside a container, not on my local machine).

I cannot seem to disable this behavior.  Where does the alembic migration that creates the `post` table live?  I want to stop it.

**Comment by igorbenav** [comment]
It's the `create_tables` event_handler on [startup](https://github.com/igorbenav/FastAPI-boilerplate/blob/main/src/app/core/setup.py). I'll add the option to do this, but you can do it yourself just changing here:

![Screenshot_20231228_185432_Chrome](https://github.com/igorbenav/FastAPI-boilerplate/assets/43156212/30c7bdc5-c2cd-49b5-8897-8e33c5f0e4d4)

You may add another parameter to the setup function and include it in the condition to create tables on startup
